apiVersion: apps/v1 # for versions before 1.9.0 
kind: Deployment
metadata:
  name: userapp-deployment
spec:
  selector:
    matchLabels:
      app: userapp-devops-project
  replicas: 2 # Deployment manifest to run 2 pods matching the template
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  template:
    metadata:
      labels:
        app: userapp-devops-project
    spec:
      containers:
      - name: userapp-devops-project
        image: chaudharys/hubint
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                    key: MYSQL_USER
                    name: userappconfigmap
            - name: MYSQL_PASSWD
              valueFrom:
                configMapKeyRef:
                    key: MYSQL_PASSWD
                    name: userappconfigmap
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                    key: MYSQL_HOST
                    name: userappconfigmap
