apiVersion: v1
kind: Service
metadata:
  name: userapp-service
  labels:
    app: userapp-devops-project
spec:
  selector:
    app: userapp-devops-project
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 31200
